name: pip2conda
channels:
  - conda-forge
dependencies:
  # build
  - pip
  - setuptools
  - setuptools-scm
  - wheel
  # install
  - grayskull >=1.0.0
  - requests
  - ruamel.yaml
  - setuptools
  - tomli
  # docs
  - myst-parser
  - sphinx
  - sphinx_rtd_theme
