name: pip2conda
channels:
  - conda-forge
dependencies:
  # build
  - pip
  - setuptools
  - setuptools-scm
  - wheel
  # install
  - grayskull
  - requests
  - setuptools
  - toml
  # docs
  - myst-parser
  - sphinx
  - sphinx_rtd_theme
